#!/usr/bin/env python
import sys
import time
import calendar

try:
    from selenium import webdriver
    from selenium.webdriver.support.ui import Select
except ImportError:
    print "Please install selenium\n(pip install selenium)"
    sys.exit(1)

driver = webdriver.Firefox()

f = open(sys.argv[1], 'r')

for line in f:
    cred = (line.strip().split(':'))
    birthdate = (cred[4].strip().split('-'))
    driver.get('***WEBSITE URL***')
    driver.get('***WEBSITE REGISTRATION URL')
    time.sleep(0.5)
    for c in cred[1]:
        driver.find_element_by_name('first_name').send_keys(c)
    for c in cred[2]:
        driver.find_element_by_name('last_name').send_keys(c)
    for c in cred[0]:
        driver.find_element_by_name('email').send_keys(c)
    for c in cred[0]:
        driver.find_element_by_name('matchemail').send_keys(c)
    for c in 'randompass123':
        driver.find_element_by_name('password').send_keys(c)
    for c in cred[3]:
        driver.find_element_by_name('ssn').send_keys(c)
    for c in '94041':
        driver.find_element_by_name('zip_code').send_keys(c)

    select = Select(driver.find_element_by_name('dob_month')).select_by_visible_text(calendar.month_name[int(birthdate[1])])
    select = Select(driver.find_element_by_name('dob_day')).select_by_visible_text(birthdate[2].lstrip("0"))
    select = Select(driver.find_element_by_name('dob_year')).select_by_visible_text(birthdate[0])
    
    driver.find_element_by_name('tos').click()
    driver.find_element_by_name('submit').click()
    time.sleep(3)

driver.close()
sys.exit(0)
